functional: write machine ID into nspawn container
As systemd v230 or newer requires /etc/machine-id on a nspawn container,
we need to write the container's own machine ID into /etc/machine-id.
Otherwise, functional tests don't start at all like:

  --- FAIL: TestKnownHostsVerification (10.80s)
    client_test.go:36: unable to detect machine PID

Fixes: https://github.com/coreos/fleet/issues/1594
See also https://github.com/systemd/systemd/pull/3014
See also https://github.com/coreos/rkt/pull/2440