functional: copy PAM configurations into nspawn containers
As CoreOS requires PAM configurations under /etc/pam.d starting from
developer version of CoreOS 104x, PAM configurations on the host need to
copied into the nspawn container. Otherwise, every sudo command fails
with messages like:

  --- FAIL: TestShutdown (1.99s)
      shutdown_test.go:43: exit status 1

Note that copying /etc/pam.d is necessary only for such setups with
sys-auth/pambase installed. Though it should be also fine for systems
where /etc/pam.d is empty, because then it should automatically fall
back to /usr/lib64/pam.d, which belongs to sys-libs/pam.

Fixes: https://github.com/coreos/fleet/issues/1591
See also https://coreos.com/blog/security-brief-coreos-linux-alpha-remote-ssh-issue.html