systemd: skip checking broken units instead of failing entirely
When querying unit states, if checking one of the units results in an error,
skip just that unit instead of returning an error.

Otherwise attempting to do `fleetctl load foo@.service` results in
fleetd doing nothing other than repeatedly logging out:

    ERROR: failed fetching unit states from UnitManager: Unit name foo@.service
    is not valid.