functional: poweroff machine using machinectl instead of systemctl
So far ReplaceMember has been checking for error, by looking up an
explicit string "Success" in stderr from "systemctl -M <ID> poweroff".
However, with systemd v229 or newer, systemctl poweroff does not print
out "Success" even if poweroff succeeded. This causes
TestKnownHostsVerification to always return error like:

  --- FAIL: TestKnownHostsVerification (2.66s)
      client_test.go:60: Failed replacing machine: poweroff failed:

Fix it by changing the systemctl call to "machinectl poweroff <ID>",
which should return error correctly. This would be better in the long
run, than checking for messages in stderr.

Fixes: https://github.com/coreos/fleet/issues/1586